/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiseapps_davacon_speex_SpeexWrapper */


#define JNI(X) JNIEXPORT Java_com_wiseapps_davacon_speex_SpeexWrapper_##X

#ifndef _Included_com_wiseapps_davacon_speex_SpeexWrapper
#define _Included_com_wiseapps_davacon_speex_SpeexWrapper
#ifdef __cplusplus
extern "C" {
#endif

///*
// * Class:     com_wiseapps_davacon_speex_SpeexWrapper
// * Method:    getSampleRate
// * Signature: (Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_wiseapps_davacon_speex_SpeexWrapper_getSampleRate
//  (JNIEnv *, jclass, jstring, jint format);
//
///*
// * Class:     com_wiseapps_davacon_speex_SpeexWrapper
// * Method:    getDuration
// * Signature: (Ljava/lang/String;)J
// */
//JNIEXPORT jdouble JNICALL Java_com_wiseapps_davacon_speex_SpeexWrapper_getDuration
//  (JNIEnv *, jclass, jstring, jint format);
//
///*
// * Class:     com_wiseapps_davacon_speex_SpeexWrapper
// * Method:    getFormat
// * Signature: (Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_wiseapps_davacon_speex_SpeexWrapper_getFormat
//  (JNIEnv *, jclass, jstring);
//
/*
 * Class:     com_wiseapps_davacon_speex_SpeexWrapper
 * Method:    read
 * Signature: (Ljava/lang/String;DDI)[B
 */
//JNIEXPORT jbyteArray JNICALL Java_com_wiseapps_davacon_speex_SpeexWrapper_read
//  (JNIEnv *, jclass, jstring, jdouble, jdouble, jint);
//
///*
// * Class:     com_wiseapps_davacon_speex_SpeexWrapper
// * Method:    write
// * Signature: (Ljava/lang/String;[BI)I
// */
//JNIEXPORT jint JNICALL Java_com_wiseapps_davacon_speex_SpeexWrapper_write
//  (JNIEnv *, jclass, jstring, jbyteArray, jint);
//
///*
// * Class:     com_wiseapps_davacon_speex_SpeexWrapper
// * Method:    encode
// * Signature: (Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_wiseapps_davacon_speex_SpeexWrapper_encode
//  (JNIEnv *, jclass, jstring, jstring);
//
///*
// * Class:     com_wiseapps_davacon_speex_SpeexWrapper
// * Method:    decode
// * Signature: (Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_wiseapps_davacon_speex_SpeexWrapper_decode
//  (JNIEnv *, jclass, jstring, jstring);
//
///*
// * Class:     com_wiseapps_davacon_speex_SpeexWrapper
// * Method:    test
// * Signature: (II)I
// */
//JNIEXPORT jint JNICALL Java_com_wiseapps_davacon_speex_SpeexWrapper_test
//  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
