/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiseapps_davacon_speex_SpeexWrapper */

#ifndef _Included_com_wiseapps_davacon_speex_SpeexWrapper
#define _Included_com_wiseapps_davacon_speex_SpeexWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiseapps_davacon_speex_SpeexWrapper
 * Method:    getInputStream
 * Signature: (Ljava/lang/String;I)Ljava/io/InputStream;
 */
JNIEXPORT jobject JNICALL Java_com_wiseapps_davacon_speex_SpeexWrapper_getInputStream
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_wiseapps_davacon_speex_SpeexWrapper
 * Method:    getOutputStream
 * Signature: (Ljava/lang/String;I)Ljava/io/OutputStream;
 */
JNIEXPORT jobject JNICALL Java_com_wiseapps_davacon_speex_SpeexWrapper_getOutputStream
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
