#========================================================================================
# generated by CascadesProjectImporter ver. 0.0.1  - 2014-05-28T17:43:16
#========================================================================================

TEMPLATE = app
TARGET = SoundRecorder

CONFIG += qt warn_on

# For cascades integration, some additional libraries are needed
# and the library path needs to be set
LIBS += -lbb -lbbcascades
LIBS +=  -lbb -lbbmultimedia -lmmrndclient -laudio_manager -lbbsystem -lasound

QT -= gui
QT += svg xmlpatterns sql network declarative xml script

MOBILITY += 

QMAKE_CFLAGS += -Wno-psabi
QMAKE_CXXFLAGS += -Wno-psabi

CONFIG(release, debug|release) {
    zygotize {
        TEMPLATE = lib
        QMAKE_CFLAGS += -fstack-protector-strong -fvisibility=hidden -mthumb -Os
        QMAKE_CXXFLAGS += -fstack-protector-strong -fvisibility=hidden -mthumb -Os
        QMAKE_LFLAGS += -Wl,-z,relro
        DEFINES += _FORTIFY_SOURCE=2
    }
}

INCLUDEPATH += src

HEADERS += \
    src/core/se/SEAudioStream.h \
    src/core/se/SEAudioStreamEngine.h \
    src/core/se/SEProject.h \
    src/core/se/SEProjectAudioStream.h \
    src/core/se/SEProjectEngine.h \
    src/core/se/SERecord.h \
    src/core/se/SERecordAudioStream.h \
    src/core/se/SESoundPlayer.h \
    src/core/se/SESoundRecorder.h \
    src/core/SPEEXConverter/RiffFile.h \
    src/core/SPEEXConverter/WaveFile.h \
    src/core/SRProject.h \
    src/ui/MainController.hpp \
    src/utils/SDCardUtil.h \
    src/utils/Loger.h \
    src/utils/SoundPlayer.h \
    src/utils/StatusEventHandler.h \
    src/core/SPEEXConverter/WaveSpeexFile.h \
    src/core/SPEEXConverter/CSource/config.h \
    src/core/SPEEXConverter/CSource/libspeex/_kiss_fft_guts.h \
    src/core/SPEEXConverter/CSource/libspeex/arch.h \
    src/core/SPEEXConverter/CSource/libspeex/cb_search_arm4.h \
    src/core/SPEEXConverter/CSource/libspeex/cb_search_bfin.h \
    src/core/SPEEXConverter/CSource/libspeex/cb_search_sse.h \
    src/core/SPEEXConverter/CSource/libspeex/cb_search.h \
    src/core/SPEEXConverter/CSource/libspeex/fftwrap.h \
    src/core/SPEEXConverter/CSource/libspeex/filterbank.h \
    src/core/SPEEXConverter/CSource/libspeex/filters_arm4.h \
    src/core/SPEEXConverter/CSource/libspeex/filters_bfin.h \
    src/core/SPEEXConverter/CSource/libspeex/filters_sse.h \
    src/core/SPEEXConverter/CSource/libspeex/filters.h \
    src/core/SPEEXConverter/CSource/libspeex/fixed_arm4.h \
    src/core/SPEEXConverter/CSource/libspeex/fixed_arm5e.h \
    src/core/SPEEXConverter/CSource/libspeex/fixed_bfin.h \
    src/core/SPEEXConverter/CSource/libspeex/fixed_debug.h \
    src/core/SPEEXConverter/CSource/libspeex/fixed_generic.h \
    src/core/SPEEXConverter/CSource/libspeex/kiss_fft.h \
    src/core/SPEEXConverter/CSource/libspeex/kiss_fftr.h \
    src/core/SPEEXConverter/CSource/libspeex/lpc_bfin.h \
    src/core/SPEEXConverter/CSource/libspeex/lpc.h \
    src/core/SPEEXConverter/CSource/libspeex/lsp_bfin.h \
    src/core/SPEEXConverter/CSource/libspeex/lsp.h \
    src/core/SPEEXConverter/CSource/libspeex/ltp_arm4.h \
    src/core/SPEEXConverter/CSource/libspeex/ltp_bfin.h \
    src/core/SPEEXConverter/CSource/libspeex/ltp_sse.h \
    src/core/SPEEXConverter/CSource/libspeex/ltp.h \
    src/core/SPEEXConverter/CSource/libspeex/math_approx.h \
    src/core/SPEEXConverter/CSource/libspeex/misc_bfin.h \
    src/core/SPEEXConverter/CSource/libspeex/modes.h \
    src/core/SPEEXConverter/CSource/libspeex/nb_celp.h \
    src/core/SPEEXConverter/CSource/libspeex/os_support.h \
    src/core/SPEEXConverter/CSource/libspeex/pseudofloat.h \
    src/core/SPEEXConverter/CSource/libspeex/quant_lsp_bfin.h \
    src/core/SPEEXConverter/CSource/libspeex/quant_lsp.h \
    src/core/SPEEXConverter/CSource/libspeex/resample_sse.h \
    src/core/SPEEXConverter/CSource/libspeex/sb_celp.h \
    src/core/SPEEXConverter/CSource/libspeex/smallft.h \
    src/core/SPEEXConverter/CSource/libspeex/stack_alloc.h \
    src/core/SPEEXConverter/CSource/libspeex/vbr.h \
    src/core/SPEEXConverter/CSource/libspeex/vorbis_psy.h \
    src/core/SPEEXConverter/CSource/libspeex/vq_arm4.h \
    src/core/SPEEXConverter/CSource/libspeex/vq_bfin.h \
    src/core/SPEEXConverter/CSource/libspeex/vq_sse.h \
    src/core/SPEEXConverter/CSource/libspeex/vq.h \
    src/core/SPEEXConverter/CSource/speex/speex_bits.h \
    src/core/SPEEXConverter/CSource/speex/speex_buffer.h \
    src/core/SPEEXConverter/CSource/speex/speex_callbacks.h \
    src/core/SPEEXConverter/CSource/speex/speex_config_types.h \
    src/core/SPEEXConverter/CSource/speex/speex_echo.h \
    src/core/SPEEXConverter/CSource/speex/speex_header.h \
    src/core/SPEEXConverter/CSource/speex/speex_jitter.h \
    src/core/SPEEXConverter/CSource/speex/speex_preprocess.h \
    src/core/SPEEXConverter/CSource/speex/speex_resampler.h \
    src/core/SPEEXConverter/CSource/speex/speex_stereo.h \
    src/core/SPEEXConverter/CSource/speex/speex_types.h \
    src/core/SPEEXConverter/CSource/speex/speex.h

SOURCES += \
    src/core/se/SEAudioStream.cpp \
    src/core/se/SEAudioStreamEngine.cpp \
    src/core/se/SEProject.cpp \
    src/core/se/SEProjectAudioStream.cpp \
    src/core/se/SEProjectEngine.cpp \
    src/core/se/SERecord.cpp \
    src/core/se/SERecordAudioStream.cpp \
    src/core/se/SESoundPlayer.cpp \
    src/core/se/SESoundRecorder.cpp \
    src/core/SPEEXConverter/RiffFile.cpp \
    src/core/SPEEXConverter/WaveFile.cpp \
    src/core/SRProject.cpp \
    src/core/SRProject_test.cpp \
    src/main.cpp \
    src/ui/MainController.cpp \
    src/utils/SDCardUtil.cpp \
    src/utils/Loger.cpp \
    src/utils/SoundPlayer.cpp \
    src/utils/StatusEventHandler.cpp \
    src/core/SPEEXConverter/WaveSpeexFile.cpp \
    src/core/SPEEXConverter/CSource/libspeex/bits.c \
    src/core/SPEEXConverter/CSource/libspeex/buffer.c \
    src/core/SPEEXConverter/CSource/libspeex/cb_search.c \
    src/core/SPEEXConverter/CSource/libspeex/exc_5_64_table.c \
    src/core/SPEEXConverter/CSource/libspeex/exc_5_256_table.c \
    src/core/SPEEXConverter/CSource/libspeex/exc_8_128_table.c \
    src/core/SPEEXConverter/CSource/libspeex/exc_10_16_table.c \
    src/core/SPEEXConverter/CSource/libspeex/exc_10_32_table.c \
    src/core/SPEEXConverter/CSource/libspeex/exc_20_32_table.c \
    src/core/SPEEXConverter/CSource/libspeex/fftwrap.c \
    src/core/SPEEXConverter/CSource/libspeex/filterbank.c \
    src/core/SPEEXConverter/CSource/libspeex/filters.c \
    src/core/SPEEXConverter/CSource/libspeex/gain_table_lbr.c \
    src/core/SPEEXConverter/CSource/libspeex/gain_table.c \
    src/core/SPEEXConverter/CSource/libspeex/hexc_10_32_table.c \
    src/core/SPEEXConverter/CSource/libspeex/hexc_table.c \
    src/core/SPEEXConverter/CSource/libspeex/high_lsp_tables.c \
    src/core/SPEEXConverter/CSource/libspeex/jitter.c \
    src/core/SPEEXConverter/CSource/libspeex/kiss_fft.c \
    src/core/SPEEXConverter/CSource/libspeex/kiss_fftr.c \
    src/core/SPEEXConverter/CSource/libspeex/lpc.c \
    src/core/SPEEXConverter/CSource/libspeex/lsp_tables_nb.c \
    src/core/SPEEXConverter/CSource/libspeex/lsp.c \
    src/core/SPEEXConverter/CSource/libspeex/ltp.c \
    src/core/SPEEXConverter/CSource/libspeex/mdf.c \
    src/core/SPEEXConverter/CSource/libspeex/modes_wb.c \
    src/core/SPEEXConverter/CSource/libspeex/modes.c \
    src/core/SPEEXConverter/CSource/libspeex/nb_celp.c \
    src/core/SPEEXConverter/CSource/libspeex/preprocess.c \
    src/core/SPEEXConverter/CSource/libspeex/quant_lsp.c \
    src/core/SPEEXConverter/CSource/libspeex/resample.c \
    src/core/SPEEXConverter/CSource/libspeex/sb_celp.c \
    src/core/SPEEXConverter/CSource/libspeex/scal.c \
    src/core/SPEEXConverter/CSource/libspeex/smallft.c \
    src/core/SPEEXConverter/CSource/libspeex/speex_callbacks.c \
    src/core/SPEEXConverter/CSource/libspeex/speex_header.c \
    src/core/SPEEXConverter/CSource/libspeex/speex.c \
    src/core/SPEEXConverter/CSource/libspeex/stereo.c \
    src/core/SPEEXConverter/CSource/libspeex/vbr.c \
    src/core/SPEEXConverter/CSource/libspeex/vq.c \
    src/core/SPEEXConverter/CSource/libspeex/window.c

RESOURCES += \
    

OTHER_FILES += \
    bar-descriptor.xml \
    assets/components/TrackItem.qml \
    assets/images/bnt_pause_default.png \
    assets/images/bnt_pause_disabled.png \
    assets/images/btn_end_default.png \
    assets/images/btn_end_disabled.png \
    assets/images/btn_forward_default.png \
    assets/images/btn_forward_disabled.png \
    assets/images/btn_pin1_disabled.png \
    assets/images/btn_pin2_disabled.png \
    assets/images/btn_pin3_disabled.png \
    assets/images/btn_pin4_disabled.png \
    assets/images/btn_play_default.png \
    assets/images/btn_play_disabled.png \
    assets/images/btn_play_selected.png \
    assets/images/btn_record_default.png \
    assets/images/btn_record_disabled.png \
    assets/images/btn_record_selected.png \
    assets/images/btn_rewind_default.png \
    assets/images/btn_rewind_disabled.png \
    assets/images/btn_sd_default.png \
    assets/images/btn_sd_disabled.png \
    assets/images/btn_send_default.png \
    assets/images/btn_send_disabled.png \
    assets/images/btn_start_default.png \
    assets/images/btn_start_disabled.png \
    assets/images/ic/ic_add.png \
    assets/images/ic/ic_clear.png \
    assets/images/ic/ic_cut.png \
    assets/images/ic/ic_delete.png \
    assets/images/ic/ic_microphone.png \
    assets/images/ic/ic_microphone_mute.png \
    assets/images/ic/ic_next.png \
    assets/images/ic/ic_pause.png \
    assets/images/ic/ic_play.png \
    assets/images/ic/ic_previous.png \
    assets/images/ic/ic_stop.png \
    assets/images/pause.png \
    assets/images/play.png \
    assets/images/play_disabled.png \
    assets/images/progress_scale.png \
    assets/images/record.png \
    assets/images/stop.png \
    assets/images/volume_cursor.png \
    assets/main_page.qml \
    assets/models/tracks_list.xml \
    assets/page_list.qml \
    assets/page_process_track.qml \
    bar-descriptor.xml \
    SoundRecorder.pro

unix:INCLUDEPATH += src/core/SPEEXConverter/CSource/speex \
src/core/SPEEXConverter/CSource/
